[package]
name = "omn-sprites-amethyst-ext"
version = "0.1.0"
authors = ["Owen Nelson <onelson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
omn-sprites = "0.1.0"
amethyst = "0.15.0"
serde_json = "1.0"